/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.ContUsuario;
import Logica.dtColaborador;
import Logica.dtFecha;
import Logica.dtProponente;
import Logica.dtUsuario;
import com.toedter.calendar.IDateEditor;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author juan
 */
public class Alta_perfil extends javax.swing.JFrame {
// variables y cosas generales;

    ContUsuario contUsu = ContUsuario.getInstance();
    boolean usuTipo;
    String imagenRuta = "COSO";
    JFileChooser navegadorArchivos = new JFileChooser();

    /**
     * Creates new form Alta_perfil
     */
    public Alta_perfil() {
        initComponents();
        String imagenRuta = null;
        JFileChooser navegadorArchivos = new JFileChooser();
        jT_direccion.enable(false);
        jT_web.enable(false);
        jtp_biografia.enable(false);
        jb_aceptar.setEnabled(false);
        this.setLocationRelativeTo(null);
        Date min = new Date("1950/01/01");
        Date max = new Date("2000/12/31");
        jdc_fechaNac.getDateEditor().setEnabled(false);
        jdc_fechaNac.setMaxSelectableDate(max);
        jdc_fechaNac.setMinSelectableDate(min);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jL_imagenP = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jb_examinar = new javax.swing.JButton();
        jrb_proponente = new javax.swing.JRadioButton();
        jrb_colaborador = new javax.swing.JRadioButton();
        jb_aceptar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jT_nick = new javax.swing.JTextField();
        jT_nombre = new javax.swing.JTextField();
        jT_apellido = new javax.swing.JTextField();
        jT_email = new javax.swing.JTextField();
        jdc_fechaNac = new com.toedter.calendar.JDateChooser();
        jT_web = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jT_direccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtp_biografia = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NickName");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 15, -1, -1));

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setText("Apellido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 81, -1, -1));

        jLabel4.setText("Email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 120, -1, -1));

        jLabel5.setText("Fecha Nacimiento");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 153, -1, -1));

        jL_imagenP.setText("Imagen");
        jPanel1.add(jL_imagenP, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 198, 148, 137));

        jLabel6.setText("Imagen ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 198, -1, -1));

        jb_examinar.setText("Examinar");
        jb_examinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_examinarActionPerformed(evt);
            }
        });
        jPanel1.add(jb_examinar, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 253, -1, -1));

        jrb_proponente.setText("Proponente");
        jrb_proponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_proponenteActionPerformed(evt);
            }
        });
        jPanel1.add(jrb_proponente, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 359, -1, -1));

        jrb_colaborador.setText("Colaborador");
        jrb_colaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_colaboradorActionPerformed(evt);
            }
        });
        jPanel1.add(jrb_colaborador, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 359, -1, -1));

        jb_aceptar.setText("Aceptar");
        jb_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_aceptarActionPerformed(evt);
            }
        });
        jPanel1.add(jb_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 429, -1, -1));

        jb_cancelar.setText("Cancelar");
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jb_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 429, -1, -1));

        jLabel7.setText("Pagina Web");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 15, -1, -1));
        jPanel1.add(jT_nick, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 9, 136, -1));
        jPanel1.add(jT_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 42, 136, -1));
        jPanel1.add(jT_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 75, 136, -1));
        jPanel1.add(jT_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 108, 136, -1));
        jPanel1.add(jdc_fechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 147, -1, -1));
        jPanel1.add(jT_web, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 9, 156, -1));

        jLabel8.setText("Direccion");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 48, -1, -1));
        jPanel1.add(jT_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 42, 156, -1));

        jLabel9.setText("Biografia");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        jtp_biografia.setColumns(20);
        jtp_biografia.setRows(5);
        jScrollPane1.setViewportView(jtp_biografia);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 240, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        limpiarTxt();
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_cancelarActionPerformed

    private void jrb_colaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_colaboradorActionPerformed
        usuTipo = false;
        jb_aceptar.setEnabled(true);
        jT_direccion.disable();
        jT_web.disable();
        jtp_biografia.disable();
        jrb_proponente.setSelected(false);

    }//GEN-LAST:event_jrb_colaboradorActionPerformed

    private void jrb_proponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_proponenteActionPerformed
        jrb_colaborador.setSelected(false);
        usuTipo = true;
        jb_aceptar.setEnabled(true);
        jT_direccion.enable();
        jT_web.enable();
        jtp_biografia.enable();
        jrb_colaborador.setSelected(false);
    }//GEN-LAST:event_jrb_proponenteActionPerformed

    private void jb_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_aceptarActionPerformed
        if (altaPerfil() == true) {
            JOptionPane.showMessageDialog(null, "Usuario agregado con exito");
            limpiarTxt();
        } else {
            // JOptionPane.showMessageDialog(null, "No se pudo agregar el usuario");
        }
    }//GEN-LAST:event_jb_aceptarActionPerformed

    private void jb_examinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_examinarActionPerformed
        selecImagen();
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_examinarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alta_perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alta_perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alta_perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alta_perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alta_perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_imagenP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jT_apellido;
    private javax.swing.JTextField jT_direccion;
    private javax.swing.JTextField jT_email;
    private javax.swing.JTextField jT_nick;
    private javax.swing.JTextField jT_nombre;
    private javax.swing.JTextField jT_web;
    private javax.swing.JButton jb_aceptar;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_examinar;
    private com.toedter.calendar.JDateChooser jdc_fechaNac;
    private javax.swing.JRadioButton jrb_colaborador;
    private javax.swing.JRadioButton jrb_proponente;
    private javax.swing.JTextArea jtp_biografia;
    // End of variables declaration//GEN-END:variables

// funciones
    private boolean controlDatos() throws Exception {

        if (jT_nick.getText() == null) {
            JOptionPane.showMessageDialog(null, "Nickname vacio");
            jT_nick.selectAll();
            jT_nick.requestFocus();
            return false;
        }
        if (jT_nombre.getText() == null) {
            JOptionPane.showMessageDialog(null, "Nombre vacio");
            jT_nombre.selectAll();
            jT_nombre.requestFocus();
            return false;
        }
        if (jT_apellido.getText() == null) {
            JOptionPane.showMessageDialog(null, "Apellido vacio");
            jT_apellido.selectAll();
            jT_apellido.requestFocus();
            return false;
        }
        if (jT_email.getText() == null) {
            JOptionPane.showMessageDialog(null, "Email vacio");
            jT_email.selectAll();
            jT_email.requestFocus();
            return false;
        }
        if (compruebaEmail(jT_email.getText()) != true) {
            JOptionPane.showMessageDialog(null, "Email incorrecto");
            jT_email.selectAll();
            jT_email.requestFocus();
            return false;
        }
        if (jdc_fechaNac == null) {
            JOptionPane.showMessageDialog(null, "Fecha nacimiento vacia");
            jdc_fechaNac.requestFocus();
            return false;
        }
        return true;
    }

    private boolean fechaok() {
        int dia = 0, mes = 0, anio = 0;
        dia = jdc_fechaNac.getDate().getDay();
        mes = jdc_fechaNac.getDate().getMonth();
        anio = jdc_fechaNac.getDate().getYear();

        int Cdia = 01, cMes = 01, Canio = 1945;
        if (dia == Cdia) {
            if (mes == cMes) {
                if (anio == Canio) {
                    return true;
                }
            }
        }
        return false;
    }

    private dtFecha getFechajdc() {
        dtFecha fecha;
        fecha = new dtFecha(Integer.toString(jdc_fechaNac.getDate().getDay()), Integer.toString(jdc_fechaNac.getDate().getMonth()), Integer.toString(jdc_fechaNac.getDate().getYear()));
        return fecha;
    }

    private boolean compruebaEmail(String email) {
        // Patrón para validar el email
        Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        Matcher mather = pattern.matcher(email);

        return mather.find();
    }

    private void limpiarTxt() {
        jT_nick.setText(" ");
        jT_nombre.setText(" ");
        jT_apellido.setText(" ");
        jT_email.setText(" ");
        jdc_fechaNac.setCalendar(null);
        jT_direccion.setText(" ");
        jT_web.setText(" ");
        jtp_biografia.setText(" ");
        jrb_colaborador.setSelected(false);
        jrb_proponente.setSelected(false);
        jT_direccion.disable();
        jT_web.disable();
        jtp_biografia.disable();
        jb_aceptar.disable();
        jL_imagenP.setIcon(null);

    }

    private boolean altaPerfil() {

        try {

            if (controlDatos() == true) {
                if (contUsu.existeUsuario(jT_nick.getText()) == false) {
                    if (usuTipo == false) {

                        dtColaborador dtCola = new dtColaborador((jT_nombre.getText()), jT_apellido.getText(), jT_nick.getText(),
                                 imagenRuta, jT_email.getText(), getFechajdc());
                        contUsu.agregarUsu(dtCola);
                        return true;
                    }

                    if (usuTipo == true) {
                        dtProponente dtprop = new dtProponente(jT_nombre.getText(), jT_apellido.getText(), jT_nick.getText(), imagenRuta, jT_email.getText(), getFechajdc(), jT_direccion.getText(), jtp_biografia.getText(), jT_web.getText());
                        contUsu.agregarUsu(dtprop);
                        return true;
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Ya existe un usuario con el mismo nickname");
                    return false;
                }
            } else {
                return false;
            }
        } catch (Exception ex) {
            Logger.getLogger(Alta_perfil.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

    private void selecImagen() {
        FileNameExtensionFilter filtroImagen = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        navegadorArchivos.setFileFilter(filtroImagen);
        navegadorArchivos.showOpenDialog(this);
        File imagen = navegadorArchivos.getSelectedFile();
        String path = navegadorArchivos.getSelectedFile().getPath();
        jL_imagenP.setIcon(new ImageIcon(path));
        ImageIcon icon = new ImageIcon(path);
        Image foto = icon.getImage();
        Image nuevaFoto = foto.getScaledInstance(jL_imagenP.getWidth(), jL_imagenP.getHeight(), Image.SCALE_DEFAULT);
        ImageIcon nuevoIcono = new ImageIcon(nuevaFoto);
        jL_imagenP.setIcon(nuevoIcono);
        //BufferedImage img= nuevoIcono;
        salvarImagen(foto);
    }

    private void salvarImagen(Image imagen) {
        BufferedImage img = (BufferedImage) imagen;
        File outputfile = new File("/home/juan/ProgAplicaciones2018/progAplicaciones/imagenesPerfil" + jT_nick.getText() + ".png");
        imagenRuta = "/home/juan/ProgAplicaciones2018/progAplicaciones/imagenesPerfil" + jT_nick.getText() + ".png";
        try {
            ImageIO.write(img, "png", outputfile);
        } catch (IOException ex) {
            Logger.getLogger(Alta_perfil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
