/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.ContPropuesta;
import Logica.ContUsuario;
import Logica.dtPropuesta;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nicolasgutierrez
 */
public class Consulta_de_Propuesta_por_Estado extends javax.swing.JInternalFrame {

    ContUsuario contUsu = ContUsuario.getInstance();
    ContPropuesta contProp= ContPropuesta.getInstance();
    /**
     * Creates new form Consulta_de_Propuesta_por_Estado
     */
    public Consulta_de_Propuesta_por_Estado() {
        initComponents();
        contProp.verificarPropHora();
        this.setSize(844, 580);
        
        jLabel1.setText("Estados");
        jButton2.setText("Cargar");
        jLabel6.setText("Propuestas en estado");
        labelestado.setText("Seleccione un estado");
        jLabel2.setText("Imagen");
        jLabel3.setText("Estado");
        txtestado.setText("Seleccione una propuesta");
        jLabel5.setText("Monto total");
        jLabel4.setText("Colaboradores");
        jButton1.setText("Cancelar");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablepropuestas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablepropuesta = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtestado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablacolaboradores = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtmontotoal = new javax.swing.JTextField();
        txtimagen = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableestados = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        labelestado = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablepropuestas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Titulo"
            }
        ));
        tablepropuestas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablepropuestasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablepropuestas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 130, 250));

        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 36, -1, 20));

        tablepropuesta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Descripcion", "Lugar", "Fecha", "Precio entrada", "Monto requerido"
            }
        ));
        jScrollPane2.setViewportView(tablepropuesta);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 67, 610, 97));

        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 181, -1, -1));

        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 181, -1, -1));
        getContentPane().add(txtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 176, 206, -1));

        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, -1, -1));

        tablacolaboradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nickname"
            }
        ));
        jScrollPane3.setViewportView(tablacolaboradores);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 247, 168));

        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 320, -1, -1));
        getContentPane().add(txtmontotoal, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 342, 89, -1));
        getContentPane().add(txtimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 208, 100, 100));

        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 130, -1));

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 490, -1, -1));

        tableestados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre"
            }
        ));
        tableestados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableestadosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableestados);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 130, 150));

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 80, -1));

        getContentPane().add(labelestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         List<String> estados= contProp.listarEstados();
        DefaultTableModel modelo2=(DefaultTableModel) tableestados.getModel();
        modelo2.setRowCount(0);
        for(int x=0;x<estados.size();x++){
            String e=estados.get(x);
            Object[] dat2={e};
            modelo2.addRow(dat2);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableestadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableestadosMouseClicked
        // TODO add your handling code here:
        vaciarTablas();
        int row=tableestados.rowAtPoint(evt.getPoint());
        int col=tableestados.columnAtPoint(evt.getPoint());
        
        List<String> propuestas= contProp.listarPropuestasPorEstado((String)tableestados.getValueAt(row, col));
        labelestado.setText((String)tableestados.getValueAt(row, col));
        DefaultTableModel modelo2=(DefaultTableModel) tablepropuestas.getModel();
        modelo2.setRowCount(0);
        for(int x=0;x<propuestas.size();x++){
            String e=propuestas.get(x);
            Object[] dat2={e};
            modelo2.addRow(dat2);
        }
    }//GEN-LAST:event_tableestadosMouseClicked

    private void tablepropuestasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablepropuestasMouseClicked
        try {
            // TODO add your handling code here:
            int row=tablepropuestas.rowAtPoint(evt.getPoint());
            int col=tablepropuestas.columnAtPoint(evt.getPoint());           
            dtPropuesta dtp=contProp.mostrarInfoPropuesta((String)tablepropuestas.getValueAt(row, col));
            
        DefaultTableModel model=(DefaultTableModel) tablepropuesta.getModel();
        model.setRowCount(0);
        Object[] dato={dtp.getTitulo(),dtp.getDescripcion(),dtp.getLugar(),dtp.getFechaRealizacion().getFecha(),dtp.getPrecioentrada(),dtp.getMontorequerido()};
        txtestado.setText(dtp.getEstado());
        txtmontotoal.setText(Integer.toString(dtp.getMontoTotal()));
        model.addRow(dato);
        DefaultTableModel model2=(DefaultTableModel) tablacolaboradores.getModel();
        model2.setRowCount(0);
        List<String> colabs=dtp.detColaboradores();
        for (int i=0;i<colabs.size();i++){
            String c=colabs.get(i);
            Object[] dat={c};
            model2.addRow(dat);      
        }            
            
        } catch (Exception ex) {
            Logger.getLogger(Consulta_de_Propuesta_por_Estado.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_tablepropuestasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelestado;
    private javax.swing.JTable tablacolaboradores;
    private javax.swing.JTable tableestados;
    private javax.swing.JTable tablepropuesta;
    private javax.swing.JTable tablepropuestas;
    private javax.swing.JTextField txtestado;
    private javax.swing.JLabel txtimagen;
    private javax.swing.JTextField txtmontotoal;
    // End of variables declaration//GEN-END:variables

public void vaciarTablas(){
    DefaultTableModel modelo=(DefaultTableModel) tablepropuesta.getModel();
    modelo.setRowCount(0);
       DefaultTableModel modelo2=(DefaultTableModel) tablacolaboradores.getModel();
    modelo2.setRowCount(0);
    
    txtestado.setText("");
    txtmontotoal.setText("");
}
    
}
