/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.iConUsuario;

/**
 *
 * @author nicolasgutierrez
 */
public class Dejar_de_Seguir_Usuario extends javax.swing.JInternalFrame {

    
    private iConUsuario ICP;
    /**
     * Creates new form Dejar_de_Seguir_Usuario
     */
    public Dejar_de_Seguir_Usuario() {
        initComponents();
    }

    public Dejar_de_Seguir_Usuario(iConUsuario icp) {
        initComponents();
        this.ICP=icp;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btndejardeseguir = new javax.swing.JButton();
        txtadejardeseguir = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtseguidor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        btndejardeseguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndejardeseguirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btndejardeseguir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtseguidor)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtadejardeseguir)))
                .addGap(186, 186, 186))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtseguidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtadejardeseguir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btndejardeseguir)
                .addContainerGap(277, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndejardeseguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndejardeseguirActionPerformed
                try{
        ICP.dejarDeSeguir(txtseguidor.getText(), txtadejardeseguir.getText());
        
        javax.swing.JOptionPane.showMessageDialog(null,"Se completo el dejar de seguir");
        // TODO add your handling code here:
        }catch(Exception ex){
         javax.swing.JOptionPane.showMessageDialog(null,ex);
        }
        
         this.txtseguidor.setText("");
         this.txtadejardeseguir.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_btndejardeseguirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndejardeseguir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtadejardeseguir;
    private javax.swing.JTextField txtseguidor;
    // End of variables declaration//GEN-END:variables
}
