/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.ContUsuario;
import java.util.Date;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nicolasgutierrez
 */
public class Registrar_Colaboracion_a_Propuesta extends javax.swing.JInternalFrame {
    ContUsuario contUsu = new ContUsuario();
    List<String> proponentes= contUsu.listarProponentes();
    /**
     * Creates new form Registrar_Colaboracion_a_Propuesta
     */
    public Registrar_Colaboracion_a_Propuesta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_proponente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_propuestas = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtmontotoal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtestado = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablecolaboradores = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablecolaborador = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtnickcolaborador = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        txtmontotoal1 = new javax.swing.JTextField();
        btnaceptar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jT_busqueda = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_proponente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Titulo", "Proponente"
            }
        ));
        jScrollPane1.setViewportView(jTable_proponente);
        if (jTable_proponente.getColumnModel().getColumnCount() > 0) {
            jTable_proponente.getColumnModel().getColumn(0).setHeaderValue("Titulo");
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 57, 220, -1));

        jLabel1.setText("Propuestas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jTable_propuestas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Descripcion", "Lugar", "Fecha", "Precio entrada", "Monto requerido"
            }
        ));
        jScrollPane2.setViewportView(jTable_propuestas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 57, 367, 97));

        jLabel5.setText("Monto total recaudado");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 166, 150, -1));
        getContentPane().add(txtmontotoal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 187, 150, -1));

        jLabel3.setText("Estado");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 166, -1, -1));
        getContentPane().add(txtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 187, 182, -1));

        tablecolaboradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nickname"
            }
        ));
        jScrollPane3.setViewportView(tablecolaboradores);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 247, 150, 240));

        jLabel2.setText("Colaboradores");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 226, -1, -1));

        tablecolaborador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Email"
            }
        ));
        jScrollPane4.setViewportView(tablecolaborador);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 247, 182, 71));

        jLabel4.setText("Colaborador");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 226, -1, -1));

        txtnickcolaborador.setText("Seleccione uno");
        getContentPane().add(txtnickcolaborador, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 226, -1, -1));

        jLabel6.setText("Tipo de retorno");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 324, -1, -1));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 345, 182, -1));

        jLabel7.setText("Monto");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 383, -1, -1));
        getContentPane().add(txtmontotoal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 377, 131, -1));

        btnaceptar.setText("Aceptar");
        getContentPane().add(btnaceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 410, 182, -1));

        btncancelar.setText("Cancelar");
        getContentPane().add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 449, 182, -1));
        getContentPane().add(jT_busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaceptar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jT_busqueda;
    private javax.swing.JTable jTable_proponente;
    private javax.swing.JTable jTable_propuestas;
    private javax.swing.JTable tablecolaborador;
    private javax.swing.JTable tablecolaboradores;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtmontotoal;
    private javax.swing.JTextField txtmontotoal1;
    private javax.swing.JLabel txtnickcolaborador;
    // End of variables declaration//GEN-END:variables

// funciones
    
    private void llenarGrilla(JTable tabla, String titulo[], List<String> atributos){
        // 
         Object[] fila = new Object[titulo.length];
         DefaultTableModel modelo=new DefaultTableModel(null,titulo);
        for (int i=0;i<atributos.size();i++) {
            String p=atributos.get(i);
            Object[] dat={p};
            modelo.addRow(dat);
        }
        tabla.setModel(modelo);
        } 
    }

